<template>
  <h2 v-if="errorMessage">{{ errorMessage }}</h2>
  <h2>最高</h2>
  <div>
    <SortableTable :rows="data" />
  </div>
  <h2>普通</h2>
  <div>
    <SortableTable :rows="data2" />
  </div>
</template>

<script>
import SortableTable from "./SortableTable.vue";

const data = [
  { id: "shkd-999", aScore: 9.9, bScore: 11.1, u: true, name: "風紀顧問の俺を馬鹿にする生意気ギャルをイカセ調教 森日向子" },
  { id: "ABW-087", aScore: 10, bScore: 10.8, u: true, name: "※胸糞NTR 最悪の鬱勃起映像 幸せを約束した大好きな彼女がおっさんに寝取られて、壊されました。 涼森れむ" },
  { id: "FSDSS-365", aScore: 10, bScore: 10.7, u: true, name: "田舎の夏休みはヤることが無いから都会で洗練された幼なじみを帰省中にキメセク漬けにして絶頂しまくり即アクメBODYに仕上げた 橋本ありな" },
  { id: "ipx-593", aScore: 10, bScore: 10.4, name: "私、新しいお義父さんに犯●れ続けています…。 二葉エマ" },
  { id: "WAAA-184", aScore: 8.3, bScore: 12, name: "鉄フックマ○コ引き裂き失禁拷問 陸上部エース ドM覚醒アクメ漬け 花狩まい" },
  { id: "SNIS-397", aScore: 8.7, bScore: 11.5, u: true, name: "わたし、犯されにゆきます。～弟を愛してしまった姉編～ 天使もえ" },
  { id: "PPPE-013", aScore: 10, bScore: 10, u: true, name: "大嫌いな義父のチ●ポがドストライクすぎて…時短中出しされていたのに延長を懇願して貪り合うような、おかわり中出し性交 楪カレン" },
  { id: "CAWD-426", aScore: 8.2, bScore: 11.2, u: true, name: "隣人のゴミ部屋で異臭中年おやじに抜かずの連撃中出し58発で孕まされた制服女子の末路… 花狩まい" },
  { id: "REAL-797", aScore: 7, bScore: 12.3, name: "今からこの大家族全員レ●プします" },
  { id: "SDDE-640", aScore: 8.7, bScore: 10.2, name: "リモまん リモートま●こコントロール:DNAをインストールするだけであの子のマ●コを遠隔操作！ クラスメイト・女教師・妹をイカセまくり！ハメまくり！" },
  { id: "HEYZO-0153", aScore: 9.8, bScore: 9, name: "性春の汗～コーチ、一発お願いします！～" },
  { id: "STARS-190", aScore: 9.8, bScore: 8.8, name: "敏感微乳乳首の●気な美少女は変態性欲者の兄の性処理玩具として毎日犯●れている 永野いち夏" },
  { id: "STARS-256", aScore: 8, bScore: 10.5, name: "生まれたての子鹿の如く崩れ落とす 1日中超ピストン性交 永野いち夏" },
  { id: "PPPE-062", aScore: 9.7, bScore: 8.6, u: true, name: "彼女が友達と旅行中、俺になついてくる彼女の妹を肉オナホに調教してやった3日間の出来事 楪カレン" },
  { id: "IPX-964", aScore: 9.3, bScore: 9, u: true, name: "「私、キメセクさせられました。。。」粘着型の元カレの嫉妬寝取り姦… 二葉エマ" },
  { id: "SNIS-991", aScore: 7.2, bScore: 11, name: "わたし、成績が悪くて今日も学校で固定されています。 夢乃あいか" },
  { id: "FSDSS-509", aScore: 10, bScore: 8, u: true, name: "新人 はにかむ、そして交わる 20歳 神木蘭 Avdebut" },
  { id: "NSFS-119", aScore: 5.7, bScore: 11.7, name: "投稿実話 妻がまわされた19 ～負けず嫌い格闘家妻の悲劇～ 三岳ゆうな" },
  { id: "SSIS-588", aScore: 6.5, bScore: 11, u: true, name: "ボクを馬鹿にしたやつはユルサナイ…告白を断られた僕は今日、あのオンナ教師を媚薬復讐レ●プで恥肉輪● 香水じゅん" },
  { id: "FNEO-014", aScore: 11.4, bScore: 5.8, name: "かわいすぎるから…ぜんぶきみのせいなんだ 03 御坂りあ" },
  { id: "MIDE-934", aScore: 6.3, bScore: 10.6, u: true, name: "犯●れて…助けを求めてきた美人OLが濡れたノーブラ姿だったのでたまらず追姦レ×プしてしまった。 藍芽みずき" },
  { id: "BIG-113", aScore: 4.9, bScore: 11, name: "柚子" },
  { id: "shkd-854", aScore: 5, bScore: 10.5, name: "単独強姦マニア 噂の看板娘編 星奈あい" },
  { id: "ipx-980", aScore: 10, bScore: 5, u: true, name: "同窓会で再会したかつて愛した男とのセックスに溺れ中出し最低不倫を繰り返すワタシ… 胸糞NTR オンナを虜にするのは愛でも金でもなくSEX！ 桜空もも" },
  { id: "IPX-726", aScore: 11, bScore: 3, u: true, name: "即勃たせてくれるアゲまん☆ 呼べば即舐め 絶倫フェラチオが～るふれんど。 「全部お口に出してね」≪口中出し9連発！！≫ 桃乃木かな" },
  { id: "STARS-145", aScore: 10.2, bScore: 3, u: true, name: "いち夏、覚醒。汁まみれ 汗だく舐め合い体液どろどろ！濃密に絡み合う濃度 200％のとてつもなくイヤラシイ性交 永野いち夏" },
  { id: "GANA-2548", aScore: 10, bScore: 3, name: "マジ軟派、初撮。 1684 渋谷でうちわの無料配布をしていたら童顔美少女JDをナンパ成功！華奢な身体は巨根男優に激しく抱かれて快感に打ち震える！" },
  { id: "hmn-114", aScore: 8.7, bScore: 9.1, name: "AI洗脳 強●中出し操作 マイクロチップを埋められた初恋の男に無理やり孕ませられる 天音ゆい" },
  { id: "MIAA-146", aScore: 8.4, bScore: 9.2, name: "母の再婚相手に妹が犯されているのを見てクズ勃起。 永瀬ゆい" },
  { id: "STARS-225", aScore: 9, bScore: 8.4, u: true, name: "僕を助けてくれた大好きな女子が体育会系クズにレ × プされているのに… 青空ひかり" },
  { id: "IPX-917", aScore: 9.3, bScore: 8, u: true, name: "「家出して来たって言うから泊めてあげるけどお前ヤラせろよ。」 家出娘の末路… 征服ハメ撮りレ × プ姦 桃乃木かな" },
  { id: "STARS-368", aScore: 9.4, bScore: 7.8, name: "初めての人間ドッグで極悪医師に狙われて…セクハラ検診に悔しくもガクガク声我慢イキするOL 青空ひかり" },
  { id: "IPX-034", aScore: 8.9, bScore: 8.3, name: "売られた愛嬢 幸せな家庭を襲った DQN グループの鬼畜訪問 相沢みなみ" },
  { id: "DASD-998", aScore: 8, bScore: 9.2, u: true, name: "女体化した俺は親友に求められるがまま、受け入れて、心も女になっていた。 天然美月" },
  { id: "MIDE-909", aScore: 8, bScore: 9.2, name: "大嫌いな同級生の部屋に監禁されオシッコも許されなかった私… 七沢みあ" },
  { id: "miaa-657", aScore: 7.9, bScore: 9.3, u: true, name: "9年の刑期を終えた巨漢レ×プ魔に侵入された華奢スレンダーOLがトラウマ種付けプレスで犯●れ続けた3日間 横宮七海" },
  { id: "ipx-415", aScore: 8.2, bScore: 8.9, name: "女潜入捜査官 薬漬けにされち○ぽ奴隷と化した巨乳エリート 桜空もも" },
  { id: "SSNI-677", aScore: 9, bScore: 8, u: true, name: "可愛いからっていい気になってるありなに嫉妬した私は男友達たちに頼んで何度も復讐代行レ×プしてもらった。 橋本ありな" },
  { id: "WANZ-359", aScore: 8.3, bScore: 8.6, name: "新任女教師 残忍冷酷中出しレ × プ輪姦 つぼみ" },
  { id: "STARS-205", aScore: 9, bScore: 7.8, name: "小柄な元アイドル美少女がデカチンでイキ狂う！ 限界イカセ 何回イっても止まらない巨根超絶激ピストン 永野いち夏" },
  { id: "MIDE-558", aScore: 9.8, bScore: 7, name: "痴漢に溺れて…―この車両だけはダメだと知っていたのに…― 水卜さくら" },
  { id: "miaa-029", aScore: 7.6, bScore: 9.2, name: "オシッコ我慢させて反抗期の娘を犯る！（追撃説教ピストン） 有坂深雪" },
  { id: "IPX-641", aScore: 9.7, bScore: 7, u: true, name: "旦那への罪悪感を覚えつつ今日も義父の濃密レ●プに繰り返し絶頂を… 楓カレン" },
  { id: "wanz-891", aScore: 9, bScore: 7.7 },
  { id: "ssis-840", aScore: 7.7, bScore: 9, u: true },
  { id: "DASS-203", aScore: 8.6, bScore: 8, u: true },
  { id: "MIDE-674", aScore: 9, bScore: 7.5, name: "肩こりを軽減させるおっぱいストレッチで性感刺激マッサージ イヤと言えない無口な女子大生を狙うパーソナルトレーナー 水卜さくら" },
  { id: "SNIS-992", aScore: 7.7, bScore: 8.8, u: true, name: "女子校生鬼畜輪姦レ●プ～標的にされた性処理生徒会長～ 橋本ありな" },
  { id: "SSNI-025", aScore: 8.7, bScore: 7.7, u: true, name: "女子校生の美乳がチラリ・ポロリ 水トさくら" },
  { id: "MIDE-643", aScore: 9.5, bScore: 6.8, u: true, name: "女子大生サイレント輪姦レ × プ ～助けを呼んで周りにバレるのが怖くて声を押し殺し屈辱ケイレン絶頂～ 水卜さくら" },
  { id: "IPX-930", aScore: 8.8, bScore: 7.5, u: true },
  { id: "ROYD-082", aScore: 8.3, bScore: 8, name: "血のつながりがないと知った僕と妹… 本当は両想いなのに、他の男にヤられる妹を見てしまい欲望が爆発した僕はついに妹を犯してしまい… 花狩まい" },
  { id: "SHKD-676", aScore: 7.6, bScore: 8.7, name: "脱獄者", "otherlink": "https://www4.javhdporn.net/video/shkd-676-decensored/" },
  { id: "MTALL-044", aScore: 8.2, bScore: 8, name: "【ピンク過ぎ】が原因で乳首イジメに合い感度限界突破して乳首イキ潮吹かす女子○生 上坂めい" },
  { id: "MIAA-648", aScore: 7.3, bScore: 8.9, u: true, name: "僕を助けてくれる幼なじみがいじめっこに犯●れているのを見て勃起した 東條なつ" },
  { id: "IPX-149", aScore: 7.7, bScore: 8.2, name: "初凌辱 純潔女子大生につけ込んだ狂気ストーカーに堕とされて… 桜空もも" },
  { id: "MILK-137", aScore: 7.9, bScore: 8, name: "むしゃぶりつきたくなる超スリム清純系美少女を接吻教育 監禁拘束して全身がふやけるまで舐め倒す開発調教 倉本すみれ" },
  { id: "midv-488", aScore: 9.8, bScore: 6 },
  { id: "SHKD-951", aScore: 8.1, bScore: 7.7 },
  { id: "hmn-156", aScore: 8, bScore: 7.7, u: true, name: "初恋の新人女子マネージャーは合宿中の自由時間60分で汗だく絶倫先輩たちに寝取られ中出し輪●されています… 上坂めい" },
  { id: "IPX-660", aScore: 7.5, bScore: 8.2, u: true, name: "初恋の新人女子マネージャーは合宿中の自由時間 60 分で汗だく絶倫先輩たちに寝取られ中出し輪●されています… 上坂めい" },
  { id: "SDMF-022", aScore: 7, bScore: 8.6 },
  { id: "IPX-674", aScore: 8, bScore: 7.5, name: "ユメカウツツカ 日間 1 位 週間 1 位 月間 1 位 大人気同人コミックを S 級超単体女優で実写化！！ 桜空もも" },
  { id: "SSNI-630", aScore: 7.9, bScore: 7.6, name: "電車の中で女をイかせる競技会に参加させられた私の 1 年間の記録 天使もえ" },
  { id: "IPX-881", aScore: 7.5, bScore: 8, u: true, name: "幼少期から面倒を見てくれた中年オヤジに突然犯●れて… 親には言えない入浴約 15 分間の背徳性交 二葉エマ" },
  { id: "stars-590", aScore: 8.6, bScore: 6.8, u: true },
  { id: "SSIS-687", aScore: 8.2, bScore: 7.2, u: true, name: "大嫌いな義父の汚いイチモツを上下の穴にぶち込まれた不幸な連れ子「でも… おぞましいアレがなぜかまた欲しいの…」 香水じゅん" },
  { id: "pppe-019", aScore: 7.7, bScore: 7.6, u: true },
  { id: "stars-334", aScore: 9.2, bScore: 6 },
  { id: "pppd-552", aScore: 8.2, bScore: 7 },
  { id: "waaa-017", aScore: 9, bScore: 6 },
  { id: "SSIS-348", aScore: 8.8, bScore: 6.2, u: true, name: "「ウブでめちゃくちゃ押しに弱い」彼女の妹に欲情し、こっそりハメ続けた最低な僕。 小倉七海" },
  { id: "ipx-213", aScore: 7.6, bScore: 7.4, u: true },
  { id: "SW-132", aScore: 7.8, bScore: 7 },
  { id: "FSDSS-500", aScore: 7.3, bScore: 7.4, u: true },
  { id: "ZEAA-39", aScore: 7.3, bScore: 7.4, name: "若妻の子宮にザーメンぶっかけ 変態義父の狂った性欲 有坂深雪", "otherlink": "https://www2.javhdporn.net/video/zeaa-39" },
  { id: "HMN-222", aScore: 9, bScore: 5.6, u: true, name: "血がつながってない義理姉と弟が両親の不在中にこっそり SEX をしているのを見て発情した妹も混ざって逆 3P ハーレム中出し近親相姦 松本いちか 森日向子" },
  { id: "MIAA-604", aScore: 7.8, bScore: 6.8, u: true, name: "薬で眠らせた娘を異常絶倫のオヤジ達に売ってます。 （1 時間 / ピル服用済 / 現金のみ / 各種オプション相談） 松本いちか" },
  { id: "ROYD-102", aScore: 8.2, bScore: 6.5, name: "無防備すぎる巨乳妹と目のやり場のないメチャ狭ワンルーム同居性活 綾瀬こころ" },
  { id: "IPX-182", aScore: 7, bScore: 7.6, name: "狙われた通学路 共謀痴漢電車 岬ななみ" },
  { id: "STARS-574", aScore: 8.5, bScore: 6, name: "『親が娘にセックスを教える時代になりました。』家族で義務 SEX 性教育をすることになった日本 朝田ひまり" },
  { id: "MIAA-506", aScore: 7.8, bScore: 6.7, u: true },
  { id: "SAME-014", aScore: 6.5, bScore: 8, u: true },
  { id: "ROYD-084", aScore: 7.7, bScore: 6.8, name: "絶対に孕ませてやる！ずっと好きだった姉が結婚するので、ボクの子供を妊娠するまで 72 時間ハメまくって 1 滴残らず種付けして犯った！ 三舩みすず" },
  { id: "SHKD-859", aScore: 7.5, bScore: 7 },
  { id: "CAWD-194", aScore: 7, bScore: 7.5, name: "キモい！ダサい！童貞臭い！軽蔑の視線でこき下ろしてくるナメくさった教え子を一晩中犯し続けた修学旅行の最終日 朝比奈ななせ" },
  { id: "ipx-374", aScore: 6.7, bScore: 7.7, u: true },
  { id: "SSPD-146", aScore: 5.8, bScore: 8.6, name: "団地妻レズ調教 媚肉の交姦" },
  { id: "PPPE-089", aScore: 9.9, bScore: 4.3, u: true, name: "会社の飲み会で終電を逃した僕に「うちに泊まっていきます？」と巨乳の後輩女子が小悪魔な囁き。部屋着の胸チラ誘惑に負けて何度も SEX した 楪カレン" },
  { id: "SDMU-672", aScore: 6.5, bScore: 7.6, name: "繋がりヲタに狙われたメジャーデビュー直前のアイドルが参加したカラオケオフ会ビデオ～スカウトから 5 年 マネージャーが手塩にかけて育てた美少女はオタクを装った DQN 集団の肉便器になりました～" },
  { id: "IPX-773", aScore: 9, bScore: 5 },
  { id: "mide-580", aScore: 9, bScore: 5, u: true },
  { id: "MUM-216", aScore: 5, bScore: 9 },
  { id: "MIAA-704", aScore: 4, bScore: 10, u: true, name: "ひまりが私の好きな男と結ばれるなんて超ムカつくッ！だから…結婚前中出しレ×プしてもらったんだ… 木下ひまり" },
  { id: "SSIS-843", aScore: 8.9, bScore: 5, u: true },
  { id: "MIDE-721", aScore: 8.2, bScore: 5.7 },
  { id: "hnd-646", aScore: 9.4, bScore: 4.2 },
  { id: "MIAA-391", aScore: 6.3, bScore: 7.3 },
  { id: "REAL-810", aScore: 6.5, bScore: 7 },
  { id: "ibw-723", aScore: 8, bScore: 5.3 },
  { id: "SVDVD-878", aScore: 6, bScore: 7.3 },
  { id: "MIDV-204", aScore: 8.7, bScore: 4.5, u: true },
  { id: "STARS-087", aScore: 9, bScore: 4 },
  { id: "HMN-120", aScore: 8, bScore: 5 },
  { id: "rbd-907", aScore: 5.3, bScore: 7.7 },
  { id: "SNIS-534", aScore: 4.7, bScore: 8.3, u: true },
  { id: "MUDR-124", aScore: 6, bScore: 6.8 },
  { id: "SHKD-546", aScore: 5.8, bScore: 7, u: true },
  { id: "stars-281", aScore: 9, bScore: 3.7 },
  { id: "ABW-032", aScore: 8.7, bScore: 4, u: true },
  { id: "SHKD-856", aScore: 6.5, bScore: 6.2 },
  { id: "APNS-302", aScore: 7.9, bScore: 4.7 },
  { id: "STARS-109", aScore: 5.6, bScore: 7 },
  { id: "SHKD-869", aScore: 5.5, bScore: 7.1 },
  { id: "CAWD-419", aScore: 5, bScore: 7.6, u: true },
  { id: "IPZZ-046", aScore: 9, bScore: 3.5 },
  { id: "ADN-210", aScore: 5.8, bScore: 6.6, u: true },
  { id: "ATID-522", aScore: 5.7, bScore: 6.6, u: true },
  { id: "ssni-569", aScore: 7.2, bScore: 5 },
  { id: "STARS-495", aScore: 5.7, bScore: 6.5 },
  { id: "MIDE-595", aScore: 9, bScore: 3, u: true },
  { id: "SDAM-014", aScore: 7, bScore: 5 },
  { id: "SHKD-996", aScore: 6, bScore: 6, u: true },
  { id: "midv-041", aScore: 7.9, bScore: 4, u: true },
  { id: "SVDVD-750", aScore: 6, bScore: 5.9 },
  { id: "MVSD-525", aScore: 6.3, bScore: 5.5, u: true },
  { id: "MIDE-525", aScore: 6, bScore: 5.7 },
  { id: "ssis-389", aScore: 5.7, bScore: 6, u: true },
  { id: "IPX-203", aScore: 5, bScore: 6.7 },
  { id: "DASS-054", aScore: 6.2, bScore: 5.4, u: true },
  { id: "ROYD-112", aScore: 6, bScore: 5.5, u: true },
  { id: "SSIS-502", aScore: 5.5, bScore: 6, u: true },
  { id: "MIAA-520", aScore: 5.7, bScore: 5.6 },
  { id: "MUDR-197", aScore: 6.6, bScore: 4.6 },
  { id: "MIDE-007", aScore: 4.2, bScore: 7, u: true },
  { id: "SSNI-325", aScore: 8, bScore: 3 },
  { id: "MIDV-185", aScore: 5, bScore: 6, u: true },
  { id: "FSDSS-378", aScore: 4.7, bScore: 6.3 },
  { id: "IPX-385", aScore: 7.8, bScore: 3 },
  { id: "WAAA-087", aScore: 6.8, bScore: 4 },
  { id: "SSIS-306", aScore: 7.5, bScore: 3, u: true },
  { id: "CAWD-041", aScore: 4.6, bScore: 5.8 },
  { id: "MIDV-484", aScore: 8.3, bScore: 2 },
  { id: "GANA-2652", aScore: 7.8, bScore: 2.3 },
  { id: "IPX-699", aScore: 4, bScore: 6.1, u: true },
  { id: "PIYO-027", aScore: 5, bScore: 5 },
  { id: "HUNT-081", aScore: 4, bScore: 6 },
  { id: "HMN-152", aScore: 2, bScore: 7.9, u: true },
  { id: "DVDMS-002", aScore: 3.8, bScore: 6 },
  { id: "HNDS-075", aScore: 5, bScore: 4.7 },
  { id: "ssis-549", aScore: 7.6, bScore: 2, u: true },
  { id: "SNIS-311", aScore: 4.5, bScore: 5 },
  { id: "HBAD-640", aScore: 5.2, bScore: 4.2 },
  { id: "STARS-248", aScore: 3.2, bScore: 6 },
  { id: "ssis-569", aScore: 8, bScore: 1, u: true },
  { id: "stars-262", aScore: 7, bScore: 2 },
  { id: "STARS-413", aScore: 6, bScore: 3 },
  { id: "HMN-127", aScore: 5, bScore: 4 },
  { id: "CAWD-406", aScore: 5, bScore: 4, u: true },
  { id: "DCOL-017", aScore: 4, bScore: 5 },
  { id: "CAWD-377", aScore: 4.7, bScore: 4, u: true },
  { id: "ABP-874", aScore: 3.8, bScore: 5 },
  { id: "BONY-016", aScore: 3.1, bScore: 5.7 },
  { id: "STARS-042", aScore: 1, bScore: 7.6, u: true },
  { id: "MIDE-422", aScore: 5, bScore: 3 },
  { id: "ABW-018", aScore: 4, bScore: 4 },
  { id: "IPZZ-008", aScore: 4, bScore: 4, u: true },
  { id: "STARS-250", aScore: 4, bScore: 4, u: true },
  { id: "hnd-661", aScore: 8.9, bScore: 9, u: true, name: "睨まれても嫌がられても俺は平然と孕ませて犯ル 有坂深雪" },
  { id: "milk-189", aScore: 7.8, bScore: 7 },
  { id: "waaa-028", aScore: 8.8, bScore: 6 },
  { id: "wanz-329", aScore: 9.1, bScore: 4 },
  { id: "wanz-853", aScore: 8.6, bScore: 2.6 },
  { id: "ssis-494", aScore: 9, bScore: 7 },
  { id: "ssis-018", aScore: 7.5, bScore: 5 },
  { id: "midv-131", aScore: 8.4, bScore: 6.3, u: true },
  { id: "pred-403", aScore: 10, bScore: 0.8, u: true },
  { id: "dass-043", aScore: 6, bScore: 7.8, u: true },
  { id: "midv-162", aScore: 7, bScore: 0.1, u: true },
  { id: "mide-872", aScore: 9, bScore: 4, u: true },
  { id: "pppe-052", aScore: 8.6, bScore: 6.2, u: true },
  { id: "atid-519", aScore: 8, bScore: 8.8, u: true },
  { id: "shkd-986", aScore: 8.3, bScore: 9.8, u: true },
  { id: "rctd-526", aScore: 7.2, bScore: 8.5 },
  { id: "fc2-ppv-2805736", aScore: 9.6, bScore: 4, otherlink: "https://njav.tv/zh/v/fc2-ppv-2805736" },
  { id: "royd-117", aScore: 7.3, bScore: 3.6, u: true },
  { id: "ssis-070", aScore: 9, bScore: 8, u: true },
  { id: "royd-146", aScore: 6.7, bScore: 3 },
  { id: "angr-003", aScore: 6, bScore: 8.2 },
  { id: "midv-158", aScore: 6.2, bScore: 3.3, u: true },
  { id: "stars-621", aScore: 6.5, bScore: 7.1 },
  { id: "mudr-143", aScore: 7.7, bScore: 7.2 },
  { id: "mudr-059", aScore: 7.3, bScore: 6.5 },
  { id: "ssni-036", aScore: 6.7, bScore: 4.8, u: true },
  { id: "midv-185", aScore: 7.6, bScore: 8.6, u: true },
];
export default {
  name: "AvTable",
  components: {
    SortableTable,
  },
  // 最高判定：aScore + bScore >= 18 || aScore >= 10 || bScore >= 10
  data() {
    return {
      data: data.filter(item => item.aScore + item.bScore >= 18 || item.aScore >= 10 || item.bScore >= 10),
      data2: data.filter(item => item.aScore + item.bScore < 18 && item.aScore < 10 && item.bScore < 10)
    };
  }
};
</script>
